# Generated by Django 4.1.3 on 2022-11-03 02:15

from django.db import migrations, models
import djgeojson.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('p_type', models.CharField(max_length=20, verbose_name='type')),
                ('name', models.CharField(max_length=100)),
                ('geometry_name', models.CharField(blank=True, max_length=100, null=True)),
                ('lon', models.FloatField()),
                ('lat', models.FloatField()),
                ('distance_to_center', models.FloatField()),
                ('count_nearest_postamat', models.IntegerField()),
                ('count_nearest_pvz', models.IntegerField()),
                ('food_delivery', models.IntegerField()),
                ('digitalization', models.IntegerField()),
                ('covering_postamats', models.IntegerField()),
                ('normalize_name', models.CharField(max_length=20)),
                ('okato', models.IntegerField()),
                ('count_nearest_metro', models.IntegerField()),
                ('level_working_region', models.IntegerField()),
                ('level_sleeping_region', models.IntegerField()),
                ('count_house_flat', models.IntegerField()),
                ('population_house_flat', models.IntegerField()),
                ('population_house_square', models.IntegerField()),
                ('population_house_living_square', models.IntegerField()),
                ('count_house_flat_400', models.IntegerField()),
                ('population_house_flat_400', models.IntegerField()),
                ('population_house_square_400', models.IntegerField()),
                ('population_house_living_square_400', models.IntegerField()),
                ('count_house_flat_200', models.IntegerField()),
                ('population_house_flat_200', models.IntegerField()),
                ('population_house_square_200', models.IntegerField()),
                ('population_house_living_square_200', models.IntegerField()),
                ('geometry', djgeojson.fields.PointField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('p_type', models.CharField(max_length=20)),
                ('index', models.IntegerField()),
                ('geometry', djgeojson.fields.MultiPolygonField()),
            ],
        ),
    ]
