# Generated by Django 4.1.3 on 2022-11-03 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pobject',
            old_name='p_type',
            new_name='type',
        ),
    ]
