# Generated by Django 4.1.3 on 2022-11-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='prc_employees_small_businesses',
            field=models.FloatField(),
        ),
    ]
