# Generated by Django 4.1.3 on 2022-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_p_type_pobject_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pobject',
            old_name='count_nearest_postamat',
            new_name='count_nearest_postamats',
        ),
        migrations.AlterField(
            model_name='pobject',
            name='digitalization',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='pobject',
            name='okato',
            field=models.BigIntegerField(),
        ),
    ]
