# Generated by Django 4.1.3 on 2022-11-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_region_oktmo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pobject',
            name='geometry_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pobject',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pobject',
            name='normalize_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pobject',
            name='type',
            field=models.CharField(max_length=50, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='region',
            name='NAME',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='region',
            name='normalize_name',
            field=models.CharField(max_length=200),
        ),
    ]
