# Generated by Django 4.1.3 on 2022-11-05 20:16

from django.db import migrations
import djgeojson.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_predicthexagon_alter_pobject_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicthexagon',
            name='geometry',
            field=djgeojson.fields.PolygonField(),
        ),
    ]
